### ISSUE TITLE
Conf perd lors du split

### ISSUE THREAD

**Issue by aconits** [ATM-Consulting/dolibarr_module_scrumboard#10]
@atm-geoffrey a remarqué que des conf ont disparut, après tout c'est normal puisque le module a était split en 2
Sauf que certaines conf auraient dû rester : exemple avec l'affichage des ressources

**Comment by atm-arnaud** [comment]
Est-ce toujours d'actualité ?

**Comment by aconits** [comment]
ahah, très bonne question
Et en vérité je sais pas, mais je pense que ça ne doit plus être d'actualité
