### ISSUE TITLE
Add 2 new columns : Backlog and In Review

### ISSUE THREAD

**Issue by atm-maxime** [ATM-Consulting/dolibarr_module_scrumboard#7]
Allow to have a scrumboard with 5 columns :

- Backlog : Tasks regarding the project
- To-do : Tasks assigned, planned, explained to the assignee but not started yet
- In progress : Tasks started
- In Review : Tasks finished by the assignee, need feedback from project manager / customer
- Finished : Tasks finished, reviewed and delivered.

**Comment by aconits** [comment]
:+1:

**Comment by aconits** [comment]
done
